services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: INNER://kafka:9093,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INNER://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "soc_network_feed:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  postgres:
    ports:
      - "5432:5432"
    image: "postgres:14-alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  socnetwork:
    ports:
      - "8080:8080"
    image: socnetwork:latest
    environment:
      DB_URL_MASTER: "jdbc:postgresql://postgres:5432/soc_network"
      DB_URL_SLAVE: "jdbc:postgresql://postgres:5432/soc_network"
      REDIS_HOST: "redis"
    depends_on:
      - postgres
      - redis

  redis:
    ports:
      - "6379:6379"
    image: "redis:8-alpine"