version: '3.7'
services:
  nginx:
    image: nginx:1.21
    container_name: nginx-lb
    restart: on-failure
    networks:
      - pgnet
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4088:80"
      - "4098:8080"

  haproxy:
    image: haproxy:2.4
    container_name: haproxy-lb
    restart: "no"
    networks:
      - pgnet
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8404:8404"

  backend-1:
    image: socnetwork:latest
    container_name: socnetwork-1
    restart: "no"
    environment:
      DB_URL_MASTER: "jdbc:postgresql://haproxy:5000/soc_network"
      DB_URL_SLAVE: "jdbc:postgresql://haproxy:5001/soc_network"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9093"
    networks:
      - pgnet
    depends_on:
      - haproxy
      - redis

  backend-2:
    image: socnetwork:latest
    container_name: socnetwork-2
    restart: "no"
    environment:
      DB_URL_MASTER: "jdbc:postgresql://haproxy:5000/soc_network"
      DB_URL_SLAVE: "jdbc:postgresql://haproxy:5001/soc_network"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9093"
    networks:
      - pgnet
    depends_on:
      - haproxy
      - redis

  backend-3:
    image: socnetwork:latest
    container_name: socnetwork-3
    restart: "no"
    environment:
      DB_URL_MASTER: "jdbc:postgresql://haproxy:5000/soc_network"
      DB_URL_SLAVE: "jdbc:postgresql://haproxy:5001/soc_network"
      REDIS_HOST: "redis"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9093"
    networks:
      - pgnet
    depends_on:
      - haproxy
      - redis

  redis:
    ports:
      - "6379:6379"
    image: "redis:8-alpine"
    networks:
      - pgnet

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - pgnet

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: INNER://kafka:9093,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INNER://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "soc_network_feed:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pgnet
    depends_on:
      - zookeeper

networks:
  pgnet:
    external: true
