config {
  db {
    urlMaster = "jdbc:postgresql://localhost:5432/soc_network"
    urlMaster = ${?DB_URL_MASTER}
    urlSlave = "jdbc:postgresql://localhost:5432/soc_network"
    urlSlave = ${?DB_URL_SLAVE}
    user = "postgres"
    user = ${?DB_USER}
    password = "mysecretpassword"
    password = ${?DB_PASSWORD}
  }

  jwt {
    secret = "XWcqd6uCuMlKUXCs4Xcid8rEAQejEByJtjT2p5vVY2s="
    secret = ${?JWT_SECRET}
    issuer = "SocNetwork"
    issuer = ${?ISSUER}
    expireInSeconds = 3600
    expireInSeconds = ${?EXPIRE_IN_SECONDS}
  }

  redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
  }
}