config {
  db {
    urlMaster = "jdbc:postgresql://localhost:5432/soc_network"
    urlMaster = ${?DB_URL_MASTER}
    urlSlave = "jdbc:postgresql://localhost:5432/soc_network"
    urlSlave = ${?DB_URL_SLAVE}
    user = "postgres"
    user = ${?DB_USER}
    password = "mysecretpassword"
    password = ${?DB_PASSWORD}
  }

  jwt {
    secret = "XWcqd6uCuMlKUXCs4Xcid8rEAQejEByJtjT2p5vVY2s="
    secret = ${?JWT_SECRET}
    issuer = "SocNetwork"
    issuer = ${?ISSUER}
    expireInSeconds = 3600
    expireInSeconds = ${?EXPIRE_IN_SECONDS}
  }

  redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
  }

  consumerConfig {
    topic = "soc_network_feed"
    topic = ${?TOPIC}
    groupId = "socnetwork-notifier-group"
    groupId = ${?GROUP_ID}
    bootstrapServers = "localhost:9092"
    bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
    securityProtocol = "PLAINTEXT"
    securityProtocol = ${?KAFKA_SECURITY_PROTOCOL}
    enableAutoCommit = "false"
    enableAutoCommit = ${?ENABLE_AUTO_COMMIT}
    autoOffsetReset = "earliest"
    autoOffsetReset = ${?AUTO_OFFSET_RESET}
  }

  producerConfig {
    topic = "soc_network_feed"
    topic = ${?TOPIC}
    bootstrapServers = "localhost:9092"
    bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
    securityProtocol = "PLAINTEXT"
    securityProtocol = ${?KAFKA_SECURITY_PROTOCOL}
    retries = 2
    retries = ${?KAFKA_PRODUCER_RETRIES}
    maxBlock = 30s
    maxBlock = ${?KAFKA_PRODUCER_MAX_BLOCK}
    deliveryTimeout = 10s
    deliveryTimeout = ${?KAFKA_PRODUCER_DELIVERY_TIMEOUT}
    requestTimeout = 5s
    requestTimeout = ${?KAFKA_PRODUCER_REQUEST_TIMEOUT}
  }
}