config {
  db {
    url = "jdbc:postgresql://localhost:5432/soc_network"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "mysecretpassword"
    password = ${?DB_PASSWORD}
  }

  jwt {
    secret = "XWcqd6uCuMlKUXCs4Xcid8rEAQejEByJtjT2p5vVY2s="
    secret = ${?JWT_SECRET}
    issuer = "SocNetwork"
    issuer = ${?ISSUER}
    expireInSeconds = 3600
    expireInSeconds = ${?EXPIRE_IN_SECONDS}
  }
}